### ISSUE TITLE
Any plans to cover more exiftool features?

### ISSUE THREAD

**Issue by wormangel** [mjeanroy/exiftool#10]
Hi.
I was playing around with this library and checking the code. Very nice and seems easy to extend, but I was wondering if you're planning on giving more flexibility for the user calling the ExifTool class. Currently the 'infrastructure' foundation is awesome (stayOpen, etc), but I'm missing more on the exposing of exiftool's power.

Right now the only real options are getImageMeta and setImageMeta, which can work for simple cases but I feel the need to send arguments like '-use mwg' to exiftool, or get/set tags taking into account the Groups (options -g[NUM] and -G[NUM]).

Expanding further than my personal use case: I think the 'definitive' exiftool wrapper should give access to all of exiftool's functionalities - of course, in the most Java way possible.

I can try to help.

**Comment by mjeanroy** [comment]
Hi,

First of all, thanks for your feedback!

I agree with you, this kind of wrapper should allow you to specify any options of the native `exiftool` library (such as the `password` option which may be important in some cases).
I'm not sure how to handle it yet since some options may change the output format, but this is something I would like to implement in a future version.

**Comment by motz17** [comment]
Hi! 
thank you for providing the lib! As mentioned in an e-mail earlier, there seems to be an issue when the service is running under load. As requested, here is a small java tool, where this behavior can be   reproduced 

[exiftool.simulation.zip](https://github.com/mjeanroy/exiftool/files/1551244/exiftool.simulation.zip) ->In the ZIP file there also sits a tiny "how-to" (exiftoolsimulation.txt).

It would be great, if you could have a look at it. 
In case I can support, just drop me a mail.

**Comment by dorinionescu** [comment]
I found the following exif features that do not have a corespondent
`//case "AFAperture": tag = StandardTag.AF_APERTURE;
//case "ExposureDifference": tag = StandardTag.EXPOSURE_DIFFERENCE;
//case "FNumber": tag = StandardTag.F_NUMBER;
//case "FocusDistance": tag = StandardTag.FOCUS_DISTANCE;
//case "FocusMode": tag = StandardTag.FOCUS_MODE;
//case "FocusPosition": tag = StandardTag.FOCUS_POSITION;
//case "ImageDataSize": tag = StandardTag.IMAGE_DATA_SIZE;
//case "LensFStops": tag = StandardTag.LENS_F_STOPS;
//case "LensSpec": tag = StandardTag.LENS_SPEC;
//case "MegaPixels": tag = StandardTag.MEGA_PIXELS;
//case "Quality": tag = StandardTag.QUALITY;
`

**Comment by kjellmoens** [comment]
Is there a possibility to get all fields of an Image fields, not only the StandardTags you specify ?

**Comment by mristuccia** [comment]
Hi there, for your interest, and because this repo seems not supported anymore, I forked it and added the ability to specify any Exiftool flag or argument. I needed this feature because I for I project I'm working with I must specify the "-m" flag.
Of course some parameters could potentially cause problems with the results, it is up to you to use the right ones.
Then, if Mickael Jeanroy appears here again, I will be happy to submit a merge request. For now I will use my version.

**Comment by Dronotique** [comment]
Ths could be a good feature

**Comment by mjeanroy** [comment]
Hi all,
Sorry for this very (very) late answer but I've been very busy during last months.

@mristuccia Feel free to submit a PR, I will be happy to review it and merge it. Does your changes cover @kjellmoens use case (i.e get all tags of an image)?

**Comment by mjeanroy** [comment]
Hi all,
I have some time now to implement some of missing features.
My plan are to add a way to get exif data for images, and to be able to plug any option. After thinking about this for a while, I plan to add this:

```java
public Map<Tag, String> getImageMeta(File image, ExifToolOptions options) throws IOException {
  // ....
}
```

Where `ExifToolOptions` is an interface that must implement a single method returning list of arguments:

```java
interface ExifToolOptions {
    Collection<String> serialize();
}
```

I will provide a default implementation with dedicated builder:

```java
class StandardExifToolOptions implements ExifToolOptions {
    private final Format format;
    private final Collection<Tag> tags;
    private final boolean ignoreMinor;

   // ....

    public static class Builder {
        private Format format;
        private Collection<Tag> tags;
        boolean ignoreMinor;

        // ...
    }
}
```

This way, it will be easy to:
- Support new option in a typesafe way.
- Provide custom option by implementing custom `ExifToolOptions`.

This should solve #68 

What do you think @mristuccia?

**Comment by mristuccia** [comment]
Hi Mickael,

thanks for the update. This would be great.
As far as my specific needs, I've already forked your solution and implemented a way to pass any options. I needed this solution in a timely fashion for I project I was working on, so I resorted to doing it personally.

I didn't submit any PR because I was not sure it was the best and cleanest implementation. You'll find it in my GIT repo if you want to have a look at it.

Kind regards.

**Comment by mjeanroy** [comment]
Hi all,

In [this commit](https://github.com/mjeanroy/exiftool/commit/cd6251a1d875fcbda09d4b48e839e64acb88a712), you will find a new way to call get/set image metadata that can support exiftool options (documented [here](https://linux.die.net/man/1/exiftool)).

For now, these options are supported out of the box:
- `-m` (ignoreMinorErrors)
- `-coordFormat`
- `-dateFormat`
- `-charset`
- `-lang`
- `-duplicates`
- `-extractEmbedded`
- `-overwrite_original` and `-overwrite_original_in_place`
- `-password`
- `-E` (escapeHtml)
- `-ex` (escapeXml)
- `-use [module]`

Here is an example to get all image metadata with custom exiftool options:

```java
exifTool.getImageMeta(file, StandardOptions.builder()
    .withFormat(StandardFormat.HUMAN_READABLE)
    .withIgnoreMinorErrors(true)
    .withEscapeHtml(true)
    .withDuplicates(true)
    .withExtractEmbedded(true)
    .build()
);
```

Also, you can define your own arguments, if you are using Java 8, it should be as easy as (if you are still locked on java 7, an anonymous class should do the work):

```java
exifTool.getImageMeta(file, () -> asList("-m", "-extractEmbedded"));
```

If this is ok for you, I'll release it and publish it to maven central today or tomorrow.

**Comment by mjeanroy** [comment]
Hi,
Version 2.6.0 has just been published to maven central with latest improvement. Please, feel free to open new issue if you found a bug or if you think some features are missing ;)
