### ISSUE TITLE
CreationDate vs CreateDate

### ISSUE THREAD

**Issue by rwaldner** [mjeanroy/exiftool#11]
I just downloaded the library to check  how useful it would be for my purposes.
There is a EXIF tag 'CreateDate' (Tag ID 0x9004) which I tried to read from my pictures - and I failed.
As now looks the StandardTag.CREATION_DATE has the name 'CreationDate' but no 'CreateDate'.

Is it now something different or just a misspelled tag name?

**Comment by mjeanroy** [comment]
@rwaldner Seems to be an error, good catch!
