### ISSUE TITLE
Version Parse Failure

### ISSUE THREAD

**Issue by prabjohns-atex** [mjeanroy/exiftool#220]
Exif Tool can output a warning if there is a module mismatch.

e.g.

```
exiftool -ver
10.48 [Warning: Library version is 10.10]

```
This can cause the constructor to fail with an integer Parse error.

The constructor should be more forgibing.

**Comment by prabjohns-atex** [comment]
[See PR](https://github.com/mjeanroy/exiftool/pull/221)

**Comment by mjeanroy** [comment]
Fixed in versions:
- 2.8.0 (java >= 7)
- 3.0.0 (java <= 8)
