### ISSUE TITLE
Get all Tags from an Image

### ISSUE THREAD

**Issue by AKMANSoft** [mjeanroy/exiftool#27]
Hi I was wondering to get the Tag from an Image rather then using Standard Tags, We can use Map<String, String> to get all stags from exif output. is there a specific reason to use standard Tags?

I can add this support to read all available Tag from a file, but want to check any known issues first.

**Comment by purple52** [comment]
The current implementation passes a list of tag names to Exiftool. This is useful if there are specific tags you want to extract, and want them parsed into suitable datatypes.

@AKMANSoft is asking for the option to specify no tags, which would cause Exiftool to return all available tags, and have the result returned in an unparsed map of strings.

This is a use case I would also be interested it; I may raise a pull request for it in the near future.

**Comment by mjeanroy** [comment]
Hi @purple52, I understand your needs.
I don't have enough time to implement it for now, but feel free to submit a pull request, I would be happy to review it. Otherwise, I'll do it as soon as possible but I can't give you an estimation of when ;)

**Comment by purple52** [comment]
I have raised #29 to implement this requirement.

**Comment by mjeanroy** [comment]
@AKMANSoft @purple52 Thanks to awesome work by @purple52, I just released exiftool v2.5.0 with this new feature (should be available soon on maven central).
