### ISSUE TITLE
output is broken on systems where the defaultCharset isn't UTF-8

### ISSUE THREAD

**Issue by sam** [mjeanroy/exiftool#3]
Ran into this setting up an ElasticBeanstalk app. I don't know what file.encoding is set to there, but it's not UTF-8. Since https://github.com/mjeanroy/exiftool/blob/master/src/main/java/com/thebuzzmedia/exiftool/commons/io/IOs.java#L54 doesn't specify an encoding it looks like it'll just use `defaultCharset`, which comes from `file.encoding`.

You can fix it by setting `java -Dfile.encoding=UTF-8 ...`, but since exiftool is known to input/output UTF-8 unless explicitly set to something else with `-L CHARSET` (see: http://www.sno.phy.queensu.ca/~phil/exiftool/faq.html#Q10), it seems like the Input/Output streams really should explicitly open with UTF-8 instead of `defaultCharset` and then this would've been a non-issue.

Hopefully that makes sense.

**Comment by mjeanroy** [comment]
Thanks for your feedback and your PR, new version will be available on maven central soon.
