### ISSUE TITLE
TagHandler is broken when tag values contain ': ' sequences.

### ISSUE THREAD

**Issue by sam** [mjeanroy/exiftool#4]
If I:

```bash
$ exiftool -Caption-Abstract="Bob: The worst human I know." sample.jpg
```

Then try to use `exiftool-lib` to extract Caption-Abstract, it breaks.

The problem is in TagHandler. This:

```java
// Now, we are sure we can process line.
String[] pair = TAG_VALUE_PATTERN.split(line);
if (pair != null && pair.length == 2) {
```

Should be this:

```java
// Now, we are sure we can process line.
String[] pair = TAG_VALUE_PATTERN.split(line, 2);
if (pair != null && pair.length == 2) {
```

According to the docs for `split`:

> The *limit* parameter controls the number of times the pattern is applied and therefore affects the length of the resulting array. If the limit n is greater than zero then the pattern will be applied at most n - 1 times, the array's length will be no greater than n, and the array's last entry will contain all input beyond the last matched delimiter.

So we want `split(line, 2)`, not `split(line)`. Because in my example above you'd get `pair.length == 3` and it would be silently skipped.

Also, it seems like a `log.warn("Skipped: %s", line);` would be justified in the `else` for that `if`.

Thanks, -Sam

**Comment by mjeanroy** [comment]
Thanks for your feedback and your PR, new version will be available on maven central soon.
