### ISSUE TITLE
Utilising Exiftool's camera/lens id database

### ISSUE THREAD

**Issue by progo** [mjeanroy/exiftool#77]
Thank your for maintaining this great wrapper.

I'm getting this discrepancy between standalone Exiftool and using the wrapper.

    (~/panasonic-test-material) exiftool -j sample.jpg | grep LensID
      "LensID": "Lumix G Vario 35-100mm F4.0-5.6 Asph. Mega OIS",

The same value comes as a numerical value in the wrapper:

    DEBUG  - Read Tag [name=UnspecifiedTag{name: "LensID"}, value=2 23 10]

I'm invoking the ExifTool object with `.getImageMeta(f)` so I should be getting everything. Debug messages agree:

    DEBUG  - Image Meta Processed [queried 210, found 210 values]

So my inquiry is whether there's something could be done to get Exiftool return the full string model?

**Comment by mjeanroy** [comment]
@progo Do you think it could be possible for you to send me an image with the issue, so that I can test it (and reproduce it)?

**Comment by progo** [comment]
Sure. Here's a sample, taken by me, free to use.
![2020-05-31-16-00-P1020902](https://user-images.githubusercontent.com/667146/83357962-80c4b700-a378-11ea-9b05-63745c0c7fcf.jpg)

**Comment by mjeanroy** [comment]
@progo When you call `.getImageMeta(f)`, do not forget to specify the output format you want. By default, it will use numeric output, you may want to use human readable output:

```java
exifTool.getImageMeta(image, StandardFormat.HUMAN_READABLE);
``` 

[I just add a unit test](https://github.com/mjeanroy/exiftool/commit/f781eccb58cac73c1a674ebfac64b17b9516f87b) showing you that the output is now correct (if you want me to remove your image from this repository, please let me know, I'll do it, no problem).

**Comment by progo** [comment]
Thank you. This clears out my problem. :)
