### ISSUE TITLE
exiftool.close doesn't clean up perl processes?

### ISSUE THREAD

**Issue by sam** [mjeanroy/exiftool#8]
I've got the following Scala code in an Akka Actor:

```
  var exiftool: ExifTool = null

  @throws[Exception](classOf[Exception])
  override def preStart(): Unit = {
    super.preStart()

    val executable = ResourceManager(s"/support/Image-ExifTool-$version.zip").toFile / "exiftool"
    executable.setExecutable(true)

    exiftool = new ExifToolBuilder()
      .withPath(executable)
      .enableStayOpen()
      .build()
  }

  @throws[Exception](classOf[Exception])
  override def postStop(): Unit = {
    try { exiftool.close() }
    finally { super.postStop() }
  }
```

Hopefully pretty self-evident. When the Actor starts, it extracts exiftool from a zip file in resources, sets it to executable, and then uses it with `ExiftoolBuilder` as the path with a `StayOpenStrategy`.

When the Actor is stopped (after it's parent actor-system is shutdown or the program exits), it calls `exiftool.close()`. This doesn't seem to work though since I can have dozens of `perl` processes hanging around after a few hours of development running focused tests frequently.

It hasn't actually causes any production issues (yet) AFAIK. Just means I need to `pkill -f perl` after a few hours of development on my local machine or things start to slow down. Just wondering if I'm doing something wrong and there's additional steps to cleanly close out stay-open instances, or if there's a bug somewhere?

This is in version `2.0.2` of exiftool-lib BTW.

**Comment by mjeanroy** [comment]
Hi,
That's weird, `stop` method should close opened process.
- What OS do you use?
- Can you give me the logs (if you use logback or log4j, just enable debug level on `com.thebuzzmedia.exiftool`)?
- If you have some time, can you run integration tests on your machine and check if process are still open (checkout the project, then just run `mvn install`)?

Thank you for your feedback !

**Comment by mjeanroy** [comment]
Hi @sam,
Did you have time to check the logs?
Thank you!

**Comment by sam** [comment]
@mjeanroy Sorry, it was actually my fault. I wasn't terminating my ActorSystem in some of my specs. Fixed that, no no more zombie processes. This issue is invalid.

**Comment by mjeanroy** [comment]
No worries, thank you for your response!
